---
title: GoAIA
timezone: UTC
collections:
  puerto-rico-spring-break:
    title: Puerto Rico Spring Break
    output: true
    permalink: "/opportunity/blog/:collection/:year/:path"
  south-africa-spring-break:
    title: South Africa Spring Break
    output: true
    permalink: "/opportunity/blog/:collection/:year/:path"
  basketball-poland:
    title: Basketball - Poland
    output: true
    permalink: "/basketball/teamblogs/:collection/:year/:path"
  basketball-ethopia:
    title: Basketball - Ethopia
    output: true
    permalink: "/basketball/teamblogs/:collection/:year/:path"
  basketball-new-zealand:
    title: Basketball - New Zealand
    output: true
    permalink: "/basketball/teamblogs/:collection/:year/:path"
  basketball-czech-spain:
    title: Basketball - Czech/Spain
    output: true
    permalink: "/basketball/teamblogs/:collection/:year/:path"
  aia-team-blogs:
    title: AIA Team Blogs
    output: false
  sports-performance-armenia:
    title: Sports Performance Armenia
    output: true
    permalink: "/opportunity/blog/sports-performance/blog/:collection/:year/:path"
  sports-performance-honduras:
    title: Sports Performance Honduras
    output: true
    permalink: "/opportunity/blog/sports-performance/blog/:collection/:year/:path"
  utc-high-school:
    title: UTC High School
    output: true
    permalink: "/opportunity/blog/:collection/:year/:path"
  urban-project-la:
    title: Urban Project - Los Angeles
    output: true
    permalink: "/opportunity/blog/:collection/:year/:path"
  x-project:
    title: X-Project
    output: true
    permalink: "/opportunity/blog/:collection/:year/:path"
  track-canary:
    title: Track - Canary Islands
    output: true
    permalink: "/track/teamblogs/:collection/:year/:path"
  track-switzerland:
    title: Track - Switzerland
    output: true
    permalink: "/track/teamblogs/:collection/:year/:path"
  track-tuff:
    title: Track - Tuff Camp
    output: true
    permalink: "/track/teamblogs/:collection/:year/:path"
  soccer-portugal:
    title: Soccer - Men Portugal
    output: true
    permalink: "/soccer/teamblogs/:collection/:year/:path"
defaults:
- scope:
    path: ''
    type: pages
  values:
    byLine: ''
    layout: blog-page
- scope:
    path: ''
    type: south-africa-spring-break
  values:
    byLine: ''
    layout: blog-page
- scope:
    path: ''
    type: puerto-rico-spring-break
  values:
    byLine: ''
    layout: blog-page
- scope:
    path: ''
    type: basketball-poland
  values:
    byLine: ''
    layout: blog-page
    filter: basketball
- scope:
    path: ''
    type: basketball-ethopia
  values:
    byLine: ''
    layout: blog-page
    filter: basketball
- scope:
    path: ''
    type: basketball-new-zealand
  values:
    byLine: ''
    layout: blog-page
    filter: basketball
- scope:
    path: ''
    type: basketball-czech-spain
  values:
    byLine: ''
    layout: blog-page
    filter: basketball
- scope:
    path: ''
    type: sports-perfomance-armenia
  values:
    byLine: ''
    layout: blog-page
    filter: sports-performance
- scope:
    path: ''
    type: sports-perfomance-honduras
  values:
    byLine: ''
    layout: blog-page
    filter: sports-performance
- scope:
    path: ''
    type: utc-high-school
  values:
    byLine: ''
    layout: blog-page
- scope:
    path: ''
    type: urban-project-la
  values:
    byLine: ''
    layout: blog-page
- scope:
    path: ''
    type: x-project
  values:
    byLine: ''
    layout: blog-page
- scope:
    path: ''
    type: soccer-portugal
  values:
    byLine: ''
    layout: blog-page
    filter: soccer
- scope:
    path: ''
    type: track-tuff
  values:
    byLine: ''
    layout: blog-page
    filter: track
- scope:
    path: ''
    type: track-canary
  values:
    byLine: ''
    layout: blog-page
    filter: track
- scope:
    path: ''
    type: track-switzerland
  values:
    byLine: ''
    layout: blog-page
    filter: track
include:
- _pages
exclude:
- "/vendor/"
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md
- "*.gemspec"
keep_files:
- CNAME
- ".git"
- ".gitignore"
subtitle: Celebrating the Induction to the Hall of Faith
baseurl: 
cover: "/assets/cover.png"
logo: "/assets/logo.png"
markdown: kramdown
sass:
  style: compressed
pagination:
  enabled: true
  debug: false
  collection: all
  per_page: 5
  permalink: "/page/:num/"
  title: ":title - page :num"
  limit: 0
  sort_field: date
  sort_reverse: true
  category: posts
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2
  extension: html
  indexpage: index
plugins:
- jekyll-redirect-from
- jekyll-paginate-v2
