---
title: GoAIA
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  puerto-rico-spring-break:
    title: Puerto Rico Spring Break
    output: true
    permalink: "/teamblogs/:year/:collection/:path"
  south-africa-spring-break:
    title: South Africa Spring Break
    output: true
    permalink: "/teamblogs/:collection/:year/:path"
    layout: teamblogs
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    byLine: ''
    layout: page
- scope:
    path: ''
    type: south-africa-spring-break
  values:
    byLine: ''
    layout: blog-page
- scope:
    path: ''
    type: camps
  values:
    location: 
    start_date: 
    end_date: 
    event_id: 
    layout: page
    address: 
    type: 
- scope:
    path: ''
    type: teams
  values:
    level: 
    director: 
    director_email: 
    dates: 
    type: 
    layout: page
- scope:
    path: ''
    type: events
  values:
    location: 
    image: 
    start_date: 
    end_date: 
    layout: page
    alt_url: 
    short_description: 
    final_four: 
include:
- _pages
exclude:
- "/vendor/"
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md
- "*.gemspec"
keep_files:
- CNAME
- ".git"
- ".gitignore"
subtitle: Celebrating the Induction to the Hall of Faith
baseurl: 
cover: "/assets/cover.png"
logo: "/assets/logo.png"
markdown: kramdown
sass:
  style: compressed
pagination:
  enabled: true
  debug: true
  collection: all
  per_page: 5
  permalink: "/page/:num/"
  title: ":title - page :num"
  limit: 0
  sort_field: date
  sort_reverse: true
  category: posts
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2
  extension: html
  indexpage: index
plugins:
- jekyll-redirect-from
- jekyll-paginate-v2
