---
new_page_extension: md
auto_deploy: false
admin_path: "/teamblogs/admin"
webhook_url: 
sections:
- type: directory
  path: _south-africa-project
  label: South africa project
  create: all
  match: "**/*"
- type: directory
  path: _wrestling-central-asia
  label: Wrestling-central-asia
  create: all
  match: "**/*"
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _wrestling-ukraine
  label: Wrestling-ukraine
  create: all
  match: "**/*"
- type: directory
  path: _puerto-rico-spring-break
  label: Puerto-rico-spring-break
  create: all
  match: "**/*"
- type: directory
  path: _south-africa-spring-break
  label: South-africa-spring-break
  create: all
  match: "**/*"
- type: directory
  path: _basketball-poland
  label: Basketball-poland
  create: all
  match: "**/*"
- type: directory
  path: _aia-team-blogs
  label: Aia-team-blogs
  create: all
  match: "**/*"
- type: directory
  path: _sports-performance-armenia
  label: Sports-performance-armenia
  create: all
  match: "**/*"
- type: directory
  path: _x-project
  label: X-project
  create: all
  match: "**/*"
- type: directory
  path: _utc-high-school
  label: Utc-high-school
  create: all
  match: "**/*"
- type: directory
  path: _soccer-portugal
  label: Soccer-portugal
  create: all
  match: "**/*"
- type: directory
  path: _basketball-ethopia
  label: Basketball-ethopia
  create: all
  match: "**/*"
- type: directory
  path: _track-canary
  label: Track-canary
  create: all
  match: "**/*"
- type: directory
  path: _track-switzerland
  label: Track-switzerland
  create: all
  match: "**/*"
- type: directory
  path: _track-tuff
  label: Track-tuff
  create: all
  match: "**/*"
- type: directory
  path: _basketball-new-zealand
  label: Basketball-new-zealand
  create: all
  match: "**/*"
- type: directory
  path: _basketball-czech-spain
  label: Basketball-czech-spain
  create: all
  match: "**/*"
- type: directory
  path: _urban-project-la
  label: Urban-project-la
  create: all
  match: "**/*"
- type: directory
  path: _sports-performance-honduras
  label: Sports-performance-honduras
  create: all
  match: "**/*"
- type: directory
  path: _sports-performance-south-africa
  label: Sports-performance-south-africa
  create: all
  match: "**/*"
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
